POST https://lightrail-2.azurewebsites.net/nothing.svc
Content-Type: text/xml
SOAPAction: http://tempuri.org/INothingService/GetNothingValues

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/" 
                  xmlns:tns="http://schemas.datacontract.org/2004/07/Interstate.SoapTestService">

    <soapenv:Body>

        <tem:GetNothingValues>

            <tem:input>

                <tns:Id>12</tns:Id>

                <tns:Query>dupa</tns:Query>

            </tem:input>

            <tem:Value1>12</tem:Value1>

        </tem:GetNothingValues>

    </soapenv:Body>

</soapenv:Envelope>